# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2021-04-06 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Axfhome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AxfTopMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('img', models.CharField(max_length=168)),
                ('trackid', models.CharField(max_length=168)),
            ],
            options={
                'db_table': 'axf_topmenu',
            },
        ),
    ]
