# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2021-04-07 13:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Axfhome', '0004_axfmainshow'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='axfmainshow',
            table='axf_mainshow',
        ),
    ]
